print("/ / / / / / / / FluxHub V1 / / / / / / / /")
print("Thank you for using FluxHub")
wait(1)
print("[DEBUG] VERSION CHECKER LOADING....")
wait(1)
print("[DEBUG] VERSION - F5/1/26 (LATEST)")
wait(1)
print("[DEBUG] Installing Dependencies")
wait(2)
print("[DEBUG] Loading UILibrary")
print("[DEBUG] CRITICAL ERROR, ABORTED.")
